// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurtainService.proto

package com.smarthome.curtain.curtainservice;

public interface ClientInformationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.curtain.ClientInformation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string clientName = 1;</code>
   */
  java.lang.String getClientName();
  /**
   * <code>string clientName = 1;</code>
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string dateTime = 2;</code>
   */
  java.lang.String getDateTime();
  /**
   * <code>string dateTime = 2;</code>
   */
  com.google.protobuf.ByteString
      getDateTimeBytes();
}
