// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurtainService.proto

package com.smarthome.curtain.curtainservice;

public final class CurtainServiceProto {
  private CurtainServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_curtain_ClientInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_curtain_ClientInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_curtain_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_curtain_ServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024CurtainService.proto\022\025com.smarthome.cu" +
      "rtain\"9\n\021ClientInformation\022\022\n\nclientName" +
      "\030\001 \001(\t\022\020\n\010dateTime\030\002 \001(\t\"!\n\016ServerRespon" +
      "se\022\017\n\007message\030\001 \001(\t2x\n\016CurtainService\022f\n" +
      "\021heaterInformation\022(.com.smarthome.curta" +
      "in.ClientInformation\032%.com.smarthome.cur" +
      "tain.ServerResponse0\001B=\n$com.smarthome.c" +
      "urtain.curtainserviceB\023CurtainServicePro" +
      "toP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_smarthome_curtain_ClientInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smarthome_curtain_ClientInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_curtain_ClientInformation_descriptor,
        new java.lang.String[] { "ClientName", "DateTime", });
    internal_static_com_smarthome_curtain_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smarthome_curtain_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_curtain_ServerResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
