// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heater.proto

package com.smarthome.heater;

/**
 * <pre>
 * The request message containing the temperature, the time, heater status
 * </pre>
 *
 * Protobuf type {@code SmartHome.GetTemperatureRequest}
 */
public  final class GetTemperatureRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SmartHome.GetTemperatureRequest)
    GetTemperatureRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTemperatureRequest.newBuilder() to construct.
  private GetTemperatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTemperatureRequest() {
    temperature_ = 0D;
    status_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetTemperatureRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 9: {

            temperature_ = input.readDouble();
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (currentTime_ != null) {
              subBuilder = currentTime_.toBuilder();
            }
            currentTime_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(currentTime_);
              currentTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            status_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smarthome.heater.heaterServiceImpl.internal_static_SmartHome_GetTemperatureRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smarthome.heater.heaterServiceImpl.internal_static_SmartHome_GetTemperatureRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smarthome.heater.GetTemperatureRequest.class, com.smarthome.heater.GetTemperatureRequest.Builder.class);
  }

  public static final int TEMPERATURE_FIELD_NUMBER = 1;
  private double temperature_;
  /**
   * <code>double temperature = 1;</code>
   */
  public double getTemperature() {
    return temperature_;
  }

  public static final int CURRENT_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp currentTime_;
  /**
   * <code>.google.protobuf.Timestamp current_time = 2;</code>
   */
  public boolean hasCurrentTime() {
    return currentTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp current_time = 2;</code>
   */
  public com.google.protobuf.Timestamp getCurrentTime() {
    return currentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp current_time = 2;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getCurrentTimeOrBuilder() {
    return getCurrentTime();
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object status_;
  /**
   * <code>string status = 3;</code>
   */
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }
  /**
   * <code>string status = 3;</code>
   */
  public com.google.protobuf.ByteString
      getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (temperature_ != 0D) {
      output.writeDouble(1, temperature_);
    }
    if (currentTime_ != null) {
      output.writeMessage(2, getCurrentTime());
    }
    if (!getStatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, status_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (temperature_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, temperature_);
    }
    if (currentTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCurrentTime());
    }
    if (!getStatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, status_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smarthome.heater.GetTemperatureRequest)) {
      return super.equals(obj);
    }
    com.smarthome.heater.GetTemperatureRequest other = (com.smarthome.heater.GetTemperatureRequest) obj;

    boolean result = true;
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperature())
        == java.lang.Double.doubleToLongBits(
            other.getTemperature()));
    result = result && (hasCurrentTime() == other.hasCurrentTime());
    if (hasCurrentTime()) {
      result = result && getCurrentTime()
          .equals(other.getCurrentTime());
    }
    result = result && getStatus()
        .equals(other.getStatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperature()));
    if (hasCurrentTime()) {
      hash = (37 * hash) + CURRENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTime().hashCode();
    }
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smarthome.heater.GetTemperatureRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smarthome.heater.GetTemperatureRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The request message containing the temperature, the time, heater status
   * </pre>
   *
   * Protobuf type {@code SmartHome.GetTemperatureRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SmartHome.GetTemperatureRequest)
      com.smarthome.heater.GetTemperatureRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smarthome.heater.heaterServiceImpl.internal_static_SmartHome_GetTemperatureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smarthome.heater.heaterServiceImpl.internal_static_SmartHome_GetTemperatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smarthome.heater.GetTemperatureRequest.class, com.smarthome.heater.GetTemperatureRequest.Builder.class);
    }

    // Construct using com.smarthome.heater.GetTemperatureRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      temperature_ = 0D;

      if (currentTimeBuilder_ == null) {
        currentTime_ = null;
      } else {
        currentTime_ = null;
        currentTimeBuilder_ = null;
      }
      status_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smarthome.heater.heaterServiceImpl.internal_static_SmartHome_GetTemperatureRequest_descriptor;
    }

    @java.lang.Override
    public com.smarthome.heater.GetTemperatureRequest getDefaultInstanceForType() {
      return com.smarthome.heater.GetTemperatureRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smarthome.heater.GetTemperatureRequest build() {
      com.smarthome.heater.GetTemperatureRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smarthome.heater.GetTemperatureRequest buildPartial() {
      com.smarthome.heater.GetTemperatureRequest result = new com.smarthome.heater.GetTemperatureRequest(this);
      result.temperature_ = temperature_;
      if (currentTimeBuilder_ == null) {
        result.currentTime_ = currentTime_;
      } else {
        result.currentTime_ = currentTimeBuilder_.build();
      }
      result.status_ = status_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smarthome.heater.GetTemperatureRequest) {
        return mergeFrom((com.smarthome.heater.GetTemperatureRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smarthome.heater.GetTemperatureRequest other) {
      if (other == com.smarthome.heater.GetTemperatureRequest.getDefaultInstance()) return this;
      if (other.getTemperature() != 0D) {
        setTemperature(other.getTemperature());
      }
      if (other.hasCurrentTime()) {
        mergeCurrentTime(other.getCurrentTime());
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smarthome.heater.GetTemperatureRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smarthome.heater.GetTemperatureRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private double temperature_ ;
    /**
     * <code>double temperature = 1;</code>
     */
    public double getTemperature() {
      return temperature_;
    }
    /**
     * <code>double temperature = 1;</code>
     */
    public Builder setTemperature(double value) {
      
      temperature_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperature = 1;</code>
     */
    public Builder clearTemperature() {
      
      temperature_ = 0D;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp currentTime_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> currentTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public boolean hasCurrentTime() {
      return currentTimeBuilder_ != null || currentTime_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public com.google.protobuf.Timestamp getCurrentTime() {
      if (currentTimeBuilder_ == null) {
        return currentTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
      } else {
        return currentTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public Builder setCurrentTime(com.google.protobuf.Timestamp value) {
      if (currentTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        currentTime_ = value;
        onChanged();
      } else {
        currentTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public Builder setCurrentTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (currentTimeBuilder_ == null) {
        currentTime_ = builderForValue.build();
        onChanged();
      } else {
        currentTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public Builder mergeCurrentTime(com.google.protobuf.Timestamp value) {
      if (currentTimeBuilder_ == null) {
        if (currentTime_ != null) {
          currentTime_ =
            com.google.protobuf.Timestamp.newBuilder(currentTime_).mergeFrom(value).buildPartial();
        } else {
          currentTime_ = value;
        }
        onChanged();
      } else {
        currentTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public Builder clearCurrentTime() {
      if (currentTimeBuilder_ == null) {
        currentTime_ = null;
        onChanged();
      } else {
        currentTime_ = null;
        currentTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getCurrentTimeBuilder() {
      
      onChanged();
      return getCurrentTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCurrentTimeOrBuilder() {
      if (currentTimeBuilder_ != null) {
        return currentTimeBuilder_.getMessageOrBuilder();
      } else {
        return currentTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : currentTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp current_time = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCurrentTimeFieldBuilder() {
      if (currentTimeBuilder_ == null) {
        currentTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCurrentTime(),
                getParentForChildren(),
                isClean());
        currentTime_ = null;
      }
      return currentTimeBuilder_;
    }

    private java.lang.Object status_ = "";
    /**
     * <code>string status = 3;</code>
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     */
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = getDefaultInstance().getStatus();
      onChanged();
      return this;
    }
    /**
     * <code>string status = 3;</code>
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      status_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SmartHome.GetTemperatureRequest)
  }

  // @@protoc_insertion_point(class_scope:SmartHome.GetTemperatureRequest)
  private static final com.smarthome.heater.GetTemperatureRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smarthome.heater.GetTemperatureRequest();
  }

  public static com.smarthome.heater.GetTemperatureRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTemperatureRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetTemperatureRequest>() {
    @java.lang.Override
    public GetTemperatureRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetTemperatureRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetTemperatureRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTemperatureRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smarthome.heater.GetTemperatureRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

