// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: heater.proto

package com.smarthome.heater;

public final class heaterServiceImpl {
  private heaterServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHome_GetTemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHome_GetTemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHome_GetTemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHome_GetTemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014heater.proto\022\tSmartHome\032\037google/protob" +
      "uf/timestamp.proto\"n\n\025GetTemperatureRequ" +
      "est\022\023\n\013temperature\030\001 \001(\001\0220\n\014current_time" +
      "\030\002 \001(\0132\032.google.protobuf.Timestamp\022\016\n\006st" +
      "atus\030\003 \001(\t\")\n\026GetTemperatureResponse\022\017\n\007" +
      "message\030\001 \001(\t2j\n\rHeaterService\022Y\n\016GetTem" +
      "perature\022 .SmartHome.GetTemperatureReque" +
      "st\032!.SmartHome.GetTemperatureResponse\"\000(" +
      "\001B+\n\024com.smarthome.heaterB\021heaterService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_SmartHome_GetTemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHome_GetTemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHome_GetTemperatureRequest_descriptor,
        new java.lang.String[] { "Temperature", "CurrentTime", "Status", });
    internal_static_SmartHome_GetTemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHome_GetTemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHome_GetTemperatureResponse_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
