// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public interface SecurityEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.SecurityEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event = 1;</code>
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1;</code>
   */
  com.google.protobuf.ByteString
      getEventBytes();
}
