// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public interface SecurityCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.SecurityCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
