// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_ToggleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_ToggleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_ToggleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_ToggleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_TemperatureRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_TemperatureRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_TemperatureResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_SecurityStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_SecurityStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_SystemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_SystemResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_SecurityCommand_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_SecurityCommand_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_SecurityEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_SecurityEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026SmartHomeService.proto\022\rcom.smarthome\"" +
      "\037\n\rToggleRequest\022\016\n\006status\030\001 \001(\010\" \n\016Togg" +
      "leResponse\022\016\n\006result\030\001 \001(\010\"\024\n\022Temperatur" +
      "eRequest\"*\n\023TemperatureResponse\022\023\n\013tempe" +
      "rature\030\001 \001(\001\" \n\016SecurityStatus\022\016\n\006status" +
      "\030\001 \001(\t\"&\n\016SystemResponse\022\024\n\014acknowledged" +
      "\030\001 \001(\010\"\"\n\017SecurityCommand\022\017\n\007command\030\001 \001" +
      "(\t\"\036\n\rSecurityEvent\022\r\n\005event\030\001 \001(\t2c\n\023Li" +
      "ghtControlService\022L\n\013toggleLight\022\034.com.s" +
      "marthome.ToggleRequest\032\035.com.smarthome.T" +
      "oggleResponse\"\0002z\n\030TemperatureSensorServ" +
      "ice\022^\n\021streamTemperature\022!.com.smarthome" +
      ".TemperatureRequest\032\".com.smarthome.Temp" +
      "eratureResponse\"\0000\0012\276\001\n\025SecuritySystemSe" +
      "rvice\022P\n\014reportStatus\022\035.com.smarthome.Se" +
      "curityStatus\032\035.com.smarthome.SystemRespo" +
      "nse\"\000(\001\022S\n\rmonitorSystem\022\036.com.smarthome" +
      ".SecurityCommand\032\034.com.smarthome.Securit" +
      "yEvent\"\000(\0010\001B\'\n\025com.smarthome.serviceB\014S" +
      "erviceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_smarthome_ToggleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smarthome_ToggleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_ToggleRequest_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_smarthome_ToggleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smarthome_ToggleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_ToggleResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_smarthome_TemperatureRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_smarthome_TemperatureRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_TemperatureRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_smarthome_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_smarthome_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_TemperatureResponse_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_smarthome_SecurityStatus_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_smarthome_SecurityStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_SecurityStatus_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_smarthome_SystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_smarthome_SystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_SystemResponse_descriptor,
        new java.lang.String[] { "Acknowledged", });
    internal_static_com_smarthome_SecurityCommand_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_smarthome_SecurityCommand_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_SecurityCommand_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_com_smarthome_SecurityEvent_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_smarthome_SecurityEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_SecurityEvent_descriptor,
        new java.lang.String[] { "Event", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
