// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_ToggleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_ToggleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_ToggleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_ToggleResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_TempRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_TempRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_TempResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_TempResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_StatusReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_StatusReport_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_SystemResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_SystemResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026SmarthomeService.proto\022\rcom.smarthome\"" +
      "\037\n\rToggleRequest\022\016\n\006status\030\001 \001(\010\" \n\016Togg" +
      "leResponse\022\016\n\006result\030\001 \001(\010\"\r\n\013TempReques" +
      "t\"#\n\014TempResponse\022\023\n\013temperature\030\001 \001(\001\"\036" +
      "\n\014StatusReport\022\016\n\006report\030\001 \001(\t\"\"\n\016System" +
      "Response\022\020\n\010response\030\001 \001(\t2Z\n\014LightContr" +
      "ol\022J\n\013ToggleLight\022\034.com.smarthome.Toggle" +
      "Request\032\035.com.smarthome.ToggleResponse2e" +
      "\n\021TemperatureSensor\022P\n\021StreamTemperature" +
      "\022\032.com.smarthome.TempRequest\032\033.com.smart" +
      "home.TempResponse(\0010\0012`\n\016SecuritySystem\022" +
      "N\n\014ReportStatus\022\033.com.smarthome.StatusRe" +
      "port\032\035.com.smarthome.SystemResponse(\0010\001B" +
      "\'\n\025com.smarthome.serviceB\014ServiceProtoP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_smarthome_ToggleRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smarthome_ToggleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_ToggleRequest_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_com_smarthome_ToggleResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smarthome_ToggleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_ToggleResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_com_smarthome_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_smarthome_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_TempRequest_descriptor,
        new java.lang.String[] { });
    internal_static_com_smarthome_TempResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_smarthome_TempResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_TempResponse_descriptor,
        new java.lang.String[] { "Temperature", });
    internal_static_com_smarthome_StatusReport_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_smarthome_StatusReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_StatusReport_descriptor,
        new java.lang.String[] { "Report", });
    internal_static_com_smarthome_SystemResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_smarthome_SystemResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_SystemResponse_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
