// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public interface StatusReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.StatusReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string report = 1;</code>
   */
  java.lang.String getReport();
  /**
   * <code>string report = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportBytes();
}
