// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public interface SystemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.SystemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool acknowledged = 1;</code>
   */
  boolean getAcknowledged();
}
