// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public interface SystemResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.SystemResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 1;</code>
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
