// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {
}
