// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public interface TempRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.TempRequest)
    com.google.protobuf.MessageOrBuilder {
}
