// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public interface TempResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.TempResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double temperature = 1;</code>
   */
  double getTemperature();
}
