// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmarthomeService.proto

package com.smarthome.service;

public interface ToggleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.ToggleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true if the operation was successful
   * </pre>
   *
   * <code>bool result = 1;</code>
   */
  boolean getResult();
}
