// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmartHomeService.proto

package com.smarthome.service;

public interface ToggleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.ToggleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * true for ON, false for OFF
   * </pre>
   *
   * <code>bool status = 1;</code>
   */
  boolean getStatus();
}
