// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BulbService.proto

package com.smarthome.bulb.bulbservice;

public interface BidirectionalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.bulb.BidirectionalResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
