// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeaterService.proto

package com.smarthome.heater.heaterservice;

public final class HeaterServiceProto {
  private HeaterServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_heater_UnaryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_heater_UnaryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_heater_UnaryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_heater_UnaryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_heater_ClientInformation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_heater_ClientInformation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_smarthome_heater_ServerResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_smarthome_heater_ServerResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023HeaterService.proto\022\024com.smarthome.hea" +
      "ter\"\034\n\014UnaryRequest\022\014\n\004name\030\001 \001(\t\" \n\rUna" +
      "ryResponse\022\017\n\007message\030\001 \001(\t\"9\n\021ClientInf" +
      "ormation\022\022\n\nclientName\030\001 \001(\t\022\020\n\010dateTime" +
      "\030\002 \001(\t\"!\n\016ServerResponse\022\017\n\007message\030\001 \001(" +
      "\t2\322\001\n\rHeaterService\022[\n\020sendUnaryRequest\022" +
      "\".com.smarthome.heater.UnaryRequest\032#.co" +
      "m.smarthome.heater.UnaryResponse\022d\n\021heat" +
      "erInformation\022\'.com.smarthome.heater.Cli" +
      "entInformation\032$.com.smarthome.heater.Se" +
      "rverResponse(\001B:\n\"com.smarthome.heater.h" +
      "eaterserviceB\022HeaterServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_smarthome_heater_UnaryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_smarthome_heater_UnaryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_heater_UnaryRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_smarthome_heater_UnaryResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_smarthome_heater_UnaryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_heater_UnaryResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_com_smarthome_heater_ClientInformation_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_smarthome_heater_ClientInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_heater_ClientInformation_descriptor,
        new java.lang.String[] { "ClientName", "DateTime", });
    internal_static_com_smarthome_heater_ServerResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_smarthome_heater_ServerResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_smarthome_heater_ServerResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
