// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeaterService.proto

package com.smarthome.heater.heaterservice;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.heater.ServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
