// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeaterService.proto

package com.smarthome.heater.heaterservice;

public interface UnaryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.smarthome.heater.UnaryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
